name: CI

on:
  push:
  pull_request:

jobs:
  build-and-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org
          scope: '@openfin'
          cache: npm

      - name: Install dependencies
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm ci

      - name: Prettier (check)
        run: npm run prettier-check

      - name: ESLint
        run: npm run eslint

      - name: markdownlint
        run: npm run markdownlint

      - name: Build
        run: npm run build
